/**
 * Created by faraway on 17-8-9.
 */
/**
 * 这个文件编写常用的action types
 */

/**
 * 关于主页index数据接口的常量
 */
export const INDEX_DATA = {
  REQUEST: 'INDEX_DATA @ REQUEST',
  SUCCESS: 'INDEX_DATA @ SUCCESS',
  FAILURE: 'INDEX_DATA @ FAILURE'
}

export const SEARCH = {
  REQUEST: 'SEARCH @ REQUEST',
  SUCCESS: 'SEARCH @ SUCCESS',
  FAILURE: 'SEARCH @ FAILURE'
}

export const SEARCH_HOT = {
  REQUEST: 'SEARCH_HOT @ REQUEST',
  SUCCESS: 'SEARCH_HOT @ SUCCESS',
  FAILURE: 'SEARCH_HOT @ FAILURE'
}

export const SEARCH_HISTORY = {
  REQUEST: 'SEARCH_HISTORY @ REQUEST',
  SUCCESS: 'SEARCH_HISTORY @ SUCCESS',
  FAILURE: 'SEARCH_HISTORY @ FAILURE'
}

export const SHOPS_BY_TYPES = {
  REQUEST: 'SHOPS_BY_TYPES @ REQUEST',
  SUCCESS: 'SHOPS_BY_TYPES @ SUCCESS',
  FAILURE: 'SHOPS_BY_TYPES @ FAILURE',
  CHANGE_TYPE: 'SHOPS_BY_TYPES @ CHANGE_TYPE'
}

export const SHOP_DETAIL = {
  REQUEST: 'SHOP_DETAIL @ REQUEST',
  SUCCESS: 'SHOP_DETAIL @ SUCCESS',
  FAILURE: 'SHOP_DETAIL @ FAILURE'
}

export const SHOP_COMMENTS = {
  REQUEST: 'SHOP_COMMENTS @ REQUEST',
  SUCCESS: 'SHOP_COMMENTS @ SUCCESS',
  FAILURE: 'SHOP_COMMENTS @ FAILURE'
}
